name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Repository
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose-plugin

      - name: Build and run services with Docker Compose
        run: docker-compose -f ./projects/docker-compose.yml up -d --build

      - name: Run tests
        run: |
          # Replace with your test command(s)
          echo "Running tests..."
          curl -f http://localhost:1337/ms/api/v1/health/check || exit 1


      - name: Stop Docker Compose services
        if: always()
        run: docker-compose -f ./projects/docker-compose.yml down